In [1]:
import pandas as pd
import sys
import warnings
import numpy as np

warnings.filterwarnings("ignore")
sys.path.append('../src')
pd.set_option('display.max_columns', None)
from functions import *

# Import excel file and first cleanning

We'll clean the data a bit and keep only the columns of interest.

In [2]:
xls = pd.ExcelFile('../raw_data/NFBA_2023.xlsx')
df = pd.read_excel(xls, 4).iloc[4:205, :]

df = df.drop(columns = ['Unnamed: 1','Unnamed: 2','Unnamed: 4',
                        'Unnamed: 9','Unnamed: 10','Unnamed: 11',
                        'Unnamed: 12','Unnamed: 13','Unnamed: 14',
                        'Unnamed: 15'])

df.columns = list(df.iloc[0,:])

df = df.drop(index = 4)

df = df.drop(df.columns[[-3, -4, -5]],axis = 1)

df.columns = [i.lower().strip().replace('\n',' ').strip().replace(' ','_') for i in df.columns]

df

,country,life_exectancy,per_capita_gdp,region,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,built_up_land,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official__country_overshoot_day__(for_use_in_2024),official__country_ecological_deficit_day__(for_use_in_2024)
5,NaN,NaN,NaN,World,NaN,7953.952,0.484741,0.125184,0.263549,1.561968,0.083496,0.062704,2.58164,0.484741,0.183817,0.642539,0.136416,0.062704,1.510215,-1.071424,1.709451,NaN,2024-08-01 12:27:04.777000,NaN
6,NaN,NaN,182 Records,Total of All Countries,NaN,7912.698,0.476041,0.139064,0.257655,1.466948,0.078694,0.078036,2.55615,0.461295,0.178926,0.623182,0.156357,0.078036,1.547188,-1.008962,1.692573,1.652126,2024-08-03 15:33:04.461000,2024-08-09 12:47:04.401000
7,NaN,NaN,53 Records,Africa,NaN,1398.673,0.302925,0.149074,0.225587,0.273305,0.041939,0.043207,1.154681,0.275737,0.270469,0.288532,0.067048,0.043207,0.971084,-0.183596,0.76458,1.189063,2025-04-22 09:16:10.840000,2024-11-03 19:19:45.783000
8,NaN,NaN,30 Records,Asia-Pacific,NaN,4246.233,0.362665,0.06601,0.176103,1.458297,0.072242,0.08246,2.230318,0.298066,0.074505,0.158629,0.093909,0.08246,0.722295,-1.508023,1.476821,3.087822,2024-09-04 03:39:31.381000,2024-04-28 12:43:23.434000
9,NaN,NaN,20 Records,Central America/Caribbean,NaN,92.253,0.405099,0.122843,0.259603,0.595334,0.109949,0.106722,1.787487,0.277969,0.133192,0.279604,0.130305,0.106722,1.120296,-0.667191,1.183597,1.595549,2024-11-04 09:09:54.005000,2024-08-17 09:18:52.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Viet Nam,73.618,11032.4,Asia-Pacific,LM,98.954,0.528,0.047851,0.382687,1.306666,0.088473,0.078597,2.432274,0.401993,0.008851,0.155677,0.149952,0.078597,0.79507,-1.637204,1.610548,3.059195,2024-08-14 15:08:34.078000,2024-04-29 15:20:37.285000
201,Yemen,63.753,1779.53,Middle East/Central Asia,LM,31.155,0.255308,0.100138,0.020945,0.158586,0.058752,0.01953,0.613258,0.064427,0.086669,0.030011,0.146865,0.01953,0.347502,-0.265756,0.406073,1.764761,NaN,2024-07-26 09:26:35.899000
202,Zambia,NaN,NaN,Africa,LM,19.47,0.250613,0.09965,0.532439,0.233234,0.034109,0.06317,1.213215,0.283922,0.667052,0.620781,0.016994,0.06317,1.65192,0.438705,0.803339,0.734427,NaN,NaN
203,Zimbabwe,NaN,NaN,Africa,LI,15.331,0.258499,0.270068,0.252568,0.273872,0.003414,0.02697,1.085391,0.207019,0.270294,0.118373,0.008839,0.02697,0.631495,-0.453896,0.7187,1.718764,NaN,2024-07-31 22:38:59.775000
204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 5 to 204
Data columns (total 24 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   country                                                      183 non-null    object
 1   life_exectancy                                               177 non-null    object
 2   per_capita_gdp                                               179 non-null    object
 3   region                                                       193 non-null    object
 4   income_group                                                 183 non-null    object
 5   population_(millions)                                        197 non-null    object
 6   cropland_footprint                                           167 non-null    object
 7   grazing_footprint                                            167 non-null    object
 8   forest_product_footprint                                     167 non-null    object
 9   carbon_footprint                                             167 non-null    object
 10  fish_footprint                                               167 non-null    object
 11  built_up_land                                                167 non-null    object
 12  total_ecological_footprint_(consumption)                     196 non-null    object
 13  cropland                                                     167 non-null    object
 14  grazing_land                                                 167 non-null    object
 15  forest_land                                                  167 non-null    object
 16  fishing_ground                                               167 non-null    object
 17  built_up_land                                                167 non-null    object
 18  total_biocapacity                                            196 non-null    object
 19  ecological_(deficit)_or_reserve                              196 non-null    object
 20  number_of_earths_required                                    196 non-null    object
 21  number_of_countries_required                                 195 non-null    object
 22  official__country_overshoot_day__(for_use_in_2024)           141 non-null    object
 23  official__country_ecological_deficit_day__(for_use_in_2024)  140 non-null    object
dtypes: object(24)
memory usage: 37.6+ KB

In [4]:
# We have a huge dataframe with all the data. Let's split it according to the information it stores:

df = df.reset_index(drop = True)

reg_fp = df.iloc[:14,:]  # Information about regions
coun_fp = df.iloc[17:199,:] # Information about countries

# Let's convert the columns we can to nummeric type:

def to_num(x):
    try:
        return float(x)
    except:
        return x

for i in range(df.shape[1]):
    reg_fp.iloc[:,i] = reg_fp.iloc[:,i].apply(to_num)
    coun_fp.iloc[:,i] = coun_fp.iloc[:,i].apply(to_num)

# And drop some columns

reg_fp = reg_fp.drop(columns = ['country','life_exectancy','per_capita_gdp'])

reg_fp

reg_fp.info() # Better!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 21 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   region                                                       10 non-null     object
 1   income_group                                                 4 non-null      object
 2   population_(millions)                                        14 non-null     float64
 3   cropland_footprint                                           14 non-null     float64
 4   grazing_footprint                                            14 non-null     float64
 5   forest_product_footprint                                     14 non-null     float64
 6   carbon_footprint                                             14 non-null     float64
 7   fish_footprint                                               14 non-null     float64
 8   built_up_land                                                14 non-null     float64
 9   total_ecological_footprint_(consumption)                     14 non-null     float64
 10  cropland                                                     14 non-null     float64
 11  grazing_land                                                 14 non-null     float64
 12  forest_land                                                  14 non-null     float64
 13  fishing_ground                                               14 non-null     float64
 14  built_up_land                                                14 non-null     float64
 15  total_biocapacity                                            14 non-null     float64
 16  ecological_(deficit)_or_reserve                              14 non-null     float64
 17  number_of_earths_required                                    14 non-null     float64
 18  number_of_countries_required                                 13 non-null     float64
 19  official__country_overshoot_day__(for_use_in_2024)           14 non-null     datetime64[ns]
 20  official__country_ecological_deficit_day__(for_use_in_2024)  11 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(17), object(2)
memory usage: 2.4+ KB

In [5]:
# Let's convert the datetime columns to string dates:

reg_fp['official__country_overshoot_day__(for_use_in_2024)'] = [i.date() for i in reg_fp['official__country_overshoot_day__(for_use_in_2024)']]
reg_fp['official__country_ecological_deficit_day__(for_use_in_2024)'] = [i.date() for i in reg_fp['official__country_ecological_deficit_day__(for_use_in_2024)']]
coun_fp['official__country_overshoot_day__(for_use_in_2024)'] = [i.date() for i in coun_fp['official__country_overshoot_day__(for_use_in_2024)']]
coun_fp['official__country_ecological_deficit_day__(for_use_in_2024)'] = [i.date() for i in coun_fp['official__country_ecological_deficit_day__(for_use_in_2024)']]

coun_fp['life_exectancy'][coun_fp.life_exectancy == ' '] = np.NaN
coun_fp['life_exectancy'] = coun_fp['life_exectancy'].fillna(coun_fp['life_exectancy'].median())

In [6]:
reg_fp # Good

,region,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,built_up_land,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official__country_overshoot_day__(for_use_in_2024),official__country_ecological_deficit_day__(for_use_in_2024)
0,World,NaN,7953.952,0.484741,0.125184,0.263549,1.561968,0.083496,0.062704,2.581640,0.484741,0.183817,0.642539,0.136416,0.062704,1.510215,-1.071424,1.709451,NaN,2024-08-01,NaT
1,Total of All Countries,NaN,7912.698,0.476041,0.139064,0.257655,1.466948,0.078694,0.078036,2.556150,0.461295,0.178926,0.623182,0.156357,0.078036,1.547188,-1.008962,1.692573,1.652126,2024-08-03,2024-08-09
2,Africa,NaN,1398.673,0.302925,0.149074,0.225587,0.273305,0.041939,0.043207,1.154681,0.275737,0.270469,0.288532,0.067048,0.043207,0.971084,-0.183596,0.764580,1.189063,2025-04-22,2024-11-03
3,Asia-Pacific,NaN,4246.233,0.362665,0.066010,0.176103,1.458297,0.072242,0.082460,2.230318,0.298066,0.074505,0.158629,0.093909,0.082460,0.722295,-1.508023,1.476821,3.087822,2024-09-04,2024-04-28
4,Central America/Caribbean,NaN,92.253,0.405099,0.122843,0.259603,0.595334,0.109949,0.106722,1.787487,0.277969,0.133192,0.279604,0.130305,0.106722,1.120296,-0.667191,1.183597,1.595549,2024-11-04,2024-08-17
5,EU-27,NaN,441.224,0.929712,0.211596,0.560173,2.211752,0.167982,0.128910,4.457980,0.797165,0.123959,0.924284,0.208241,0.128910,2.227589,-2.230391,2.951884,2.001258,2024-05-03,2024-07-01
6,Middle East/Central Asia,NaN,485.043,0.599754,0.152830,0.121446,1.986622,0.071802,0.057911,2.990365,0.449774,0.174052,0.139324,0.095078,0.057911,0.916138,-2.074228,1.980092,3.264100,2024-07-03,2024-04-22
7,North America,NaN,504.818,1.109494,0.270270,0.705764,3.853724,0.110021,0.058616,6.107889,1.406469,0.244431,1.672629,0.481987,0.058616,3.864131,-2.243758,4.044383,1.580663,2024-03-31,2024-08-19
8,Other Europe,NaN,306.763,0.879072,0.119771,0.498940,2.445412,0.152652,0.050463,4.449726,1.131792,0.213903,2.219749,0.687164,0.050463,4.750889,0.301162,2.946418,0.936609,2024-05-03,NaT
9,South America,NaN,437.691,0.536603,0.593052,0.310929,0.783645,0.081813,0.153109,2.535728,0.790593,0.869814,4.175129,0.321083,0.153109,6.576576,4.040848,1.679051,0.385570,2024-08-05,NaT
10,NaN,Low Income (LI),1041.411,0.283111,0.118751,0.226434,0.153857,0.029480,0.049707,0.886303,0.251958,0.182962,0.273968,0.062952,0.049707,0.840821,-0.045482,0.586872,1.054093,2025-09-13,2024-12-13
11,NaN,Lower-Middle Income (LM),2993.661,0.290005,0.059070,0.132348,0.543919,0.049073,0.053579,1.217702,0.277935,0.087658,0.158946,0.067611,0.053579,0.728074,-0.489628,0.806310,1.672497,2025-03-28,2024-08-06
12,NaN,Upper-Middle Income (UM),2715.682,0.556006,0.191415,0.273400,2.144860,0.090636,0.110876,3.379829,0.539539,0.252792,1.055115,0.179793,0.110876,2.151062,-1.228767,2.237978,1.571237,2024-06-12,2024-08-20
13,NaN,High Income (HI),1159.948,0.942990,0.241431,0.572666,3.443447,0.171503,0.089838,5.580231,0.940076,0.238226,1.124668,0.414657,0.089838,2.860617,-2.719614,3.694990,1.950709,2024-04-08,2024-07-06

In [7]:
coun_fp = coun_fp.drop(columns = 'per_capita_gdp') # We will get this from other source with a more recent update
coun_fp.life_exectancy = [int(i) for i in coun_fp.life_exectancy]

coun_fp

,country,life_exectancy,region,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,built_up_land,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official__country_overshoot_day__(for_use_in_2024),official__country_ecological_deficit_day__(for_use_in_2024)
17,Afghanistan,61,Middle East/Central Asia,LI,40.754,0.417299,0.149562,0.055141,0.150524,0.000706,0.028232,0.801465,0.327735,0.144313,0.012981,0.000565,0.028232,0.513827,-0.287638,0.530696,1.559795,NaT,2024-08-22
18,Albania,76,Other Europe,UM,2.866,0.803378,0.205494,0.205567,0.741158,0.042637,0.073006,2.071238,0.600881,0.198147,0.223326,0.081392,0.073006,1.176752,-0.894486,1.371485,1.760131,2024-09-23,2024-07-26
19,Algeria,76,Africa,UM,45.350,0.686809,0.158904,0.136541,1.179481,0.023458,0.037775,2.222968,0.357129,0.237380,0.023912,0.007179,0.037775,0.663375,-1.559593,1.471955,3.350998,2024-09-04,2024-04-19
20,Angola,61,Africa,LM,35.027,0.231260,0.112594,0.081048,0.290260,0.081323,0.061360,0.857846,0.151753,0.804692,0.416888,0.153499,0.061360,1.588191,0.730346,0.568029,0.540140,NaT,NaT
21,Antigua and Barbuda,78,Central America/Caribbean,HI,0.100,NaN,NaN,NaN,NaN,NaN,NaN,2.936735,NaN,NaN,NaN,NaN,NaN,0.917277,-2.019458,1.944580,3.201578,2024-07-06,2024-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,"Venezuela, Bolivarian Republic of",70,South America,UM,29.267,0.341907,0.619012,0.093140,0.935627,0.075966,0.043885,2.109537,0.224860,0.612324,1.805861,0.259062,0.043885,2.945992,0.836455,1.396845,0.716070,2024-09-18,NaT
195,Viet Nam,73,Asia-Pacific,LM,98.954,0.528000,0.047851,0.382687,1.306666,0.088473,0.078597,2.432274,0.401993,0.008851,0.155677,0.149952,0.078597,0.795070,-1.637204,1.610548,3.059195,2024-08-14,2024-04-29
196,Yemen,63,Middle East/Central Asia,LM,31.155,0.255308,0.100138,0.020945,0.158586,0.058752,0.019530,0.613258,0.064427,0.086669,0.030011,0.146865,0.019530,0.347502,-0.265756,0.406073,1.764761,NaT,2024-07-26
197,Zambia,71,Africa,LM,19.470,0.250613,0.099650,0.532439,0.233234,0.034109,0.063170,1.213215,0.283922,0.667052,0.620781,0.016994,0.063170,1.651920,0.438705,0.803339,0.734427,NaT,NaT
198,Zimbabwe,71,Africa,LI,15.331,0.258499,0.270068,0.252568,0.273872,0.003414,0.026970,1.085391,0.207019,0.270294,0.118373,0.008839,0.026970,0.631495,-0.453896,0.718700,1.718764,NaT,2024-07-31

In [8]:
coun_fp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 17 to 198
Data columns (total 23 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   country                                                      182 non-null    object
 1   life_exectancy                                               182 non-null    int64
 2   region                                                       182 non-null    object
 3   income_group                                                 178 non-null    object
 4   population_(millions)                                        182 non-null    float64
 5   cropland_footprint                                           152 non-null    float64
 6   grazing_footprint                                            152 non-null    float64
 7   forest_product_footprint                                     152 non-null    float64
 8   carbon_footprint                                             152 non-null    float64
 9   fish_footprint                                               152 non-null    float64
 10  built_up_land                                                152 non-null    float64
 11  total_ecological_footprint_(consumption)                     181 non-null    float64
 12  cropland                                                     152 non-null    float64
 13  grazing_land                                                 152 non-null    float64
 14  forest_land                                                  152 non-null    float64
 15  fishing_ground                                               152 non-null    float64
 16  built_up_land                                                152 non-null    float64
 17  total_biocapacity                                            181 non-null    float64
 18  ecological_(deficit)_or_reserve                              181 non-null    float64
 19  number_of_earths_required                                    181 non-null    float64
 20  number_of_countries_required                                 181 non-null    float64
 21  official__country_overshoot_day__(for_use_in_2024)           126 non-null    object
 22  official__country_ecological_deficit_day__(for_use_in_2024)  128 non-null    object
dtypes: float64(17), int64(1), object(5)
memory usage: 32.8+ KB

# Change of country and region names for country and region ids

In [9]:
coun_fp.country.apply(to_proper_country_name).value_counts()

9 Bermuda Germany max sim:57
110 French Guiana China max sim:56
91 French Polynesia Indonesia max sim:56
120 Guadeloupe Guatemala max sim:53
101 Martinique Mauritius max sim:63
37 Réunion Peru max sim:33

Congo          2
Afghanistan    1
Paraguay       1
New Zealand    1
Nicaragua      1
              ..
Gambia         1
Georgia        1
Germany        1
Ghana          1
Zimbabwe       1
Name: country, Length: 181, dtype: int64

In [10]:
i1 = [coun_fp[coun_fp.country == 'Martinique'].index[0],
      coun_fp[coun_fp.country == 'Bermuda'].index[0],
      coun_fp[coun_fp.country == 'French Guiana'].index[0],
      coun_fp[coun_fp.country == 'French Polynesia'].index[0],
      coun_fp[coun_fp.country == 'Guadeloupe'].index[0],
      coun_fp[coun_fp.country == 'Réunion'].index[0]]

coun_fp = coun_fp.drop(index = i1) # These are small French regions, not independent countries

In [11]:
coun_fp[coun_fp.country.apply(to_proper_country_name) == 'Congo'] # Let's keep the big Congo

,country,life_exectancy,region,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,built_up_land,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official__country_overshoot_day__(for_use_in_2024),official__country_ecological_deficit_day__(for_use_in_2024)
54,Congo,63,Africa,LM,5.798,0.315974,0.068044,0.284380,0.289013,0.098954,0.061983,1.118348,0.178330,2.252636,5.078504,0.259849,0.061983,7.831302,6.712954,0.740522,0.142805,NaT,NaT
55,"Congo, Democratic Republic of",59,Africa,LI,95.241,0.179445,0.009031,0.365809,0.036372,0.013418,0.081315,0.685390,0.170321,0.214940,1.348660,0.031009,0.081315,1.846246,1.160857,0.453836,0.371234,NaT,NaT

In [12]:
coun_fp = coun_fp.drop(index = coun_fp[coun_fp.country == 'Congo'].index[0])

In [13]:
coun_fp.country.apply(to_proper_country_name).value_counts() # Perfect

Afghanistan    1
Paraguay       1
Nicaragua      1
Niger          1
Nigeria        1
              ..
Georgia        1
Germany        1
Ghana          1
Greece         1
Zimbabwe       1
Name: country, Length: 175, dtype: int64

In [14]:
coun_fp.columns

Index(['country', 'life_exectancy', 'region', 'income_group',
       'population_(millions)', 'cropland_footprint', 'grazing_footprint',
       'forest_product_footprint', 'carbon_footprint', 'fish_footprint',
       'built_up_land', 'total_ecological_footprint_(consumption)', 'cropland',
       'grazing_land', 'forest_land', 'fishing_ground', 'built_up_land',
       'total_biocapacity', 'ecological_(deficit)_or_reserve',
       'number_of_earths_required', 'number_of_countries_required',
       'official__country_overshoot_day__(for_use_in_2024)',
       'official__country_ecological_deficit_day__(for_use_in_2024)'],
      dtype='object')

In [15]:
reg_fp

,region,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,built_up_land,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official__country_overshoot_day__(for_use_in_2024),official__country_ecological_deficit_day__(for_use_in_2024)
0,World,NaN,7953.952,0.484741,0.125184,0.263549,1.561968,0.083496,0.062704,2.581640,0.484741,0.183817,0.642539,0.136416,0.062704,1.510215,-1.071424,1.709451,NaN,2024-08-01,NaT
1,Total of All Countries,NaN,7912.698,0.476041,0.139064,0.257655,1.466948,0.078694,0.078036,2.556150,0.461295,0.178926,0.623182,0.156357,0.078036,1.547188,-1.008962,1.692573,1.652126,2024-08-03,2024-08-09
2,Africa,NaN,1398.673,0.302925,0.149074,0.225587,0.273305,0.041939,0.043207,1.154681,0.275737,0.270469,0.288532,0.067048,0.043207,0.971084,-0.183596,0.764580,1.189063,2025-04-22,2024-11-03
3,Asia-Pacific,NaN,4246.233,0.362665,0.066010,0.176103,1.458297,0.072242,0.082460,2.230318,0.298066,0.074505,0.158629,0.093909,0.082460,0.722295,-1.508023,1.476821,3.087822,2024-09-04,2024-04-28
4,Central America/Caribbean,NaN,92.253,0.405099,0.122843,0.259603,0.595334,0.109949,0.106722,1.787487,0.277969,0.133192,0.279604,0.130305,0.106722,1.120296,-0.667191,1.183597,1.595549,2024-11-04,2024-08-17
5,EU-27,NaN,441.224,0.929712,0.211596,0.560173,2.211752,0.167982,0.128910,4.457980,0.797165,0.123959,0.924284,0.208241,0.128910,2.227589,-2.230391,2.951884,2.001258,2024-05-03,2024-07-01
6,Middle East/Central Asia,NaN,485.043,0.599754,0.152830,0.121446,1.986622,0.071802,0.057911,2.990365,0.449774,0.174052,0.139324,0.095078,0.057911,0.916138,-2.074228,1.980092,3.264100,2024-07-03,2024-04-22
7,North America,NaN,504.818,1.109494,0.270270,0.705764,3.853724,0.110021,0.058616,6.107889,1.406469,0.244431,1.672629,0.481987,0.058616,3.864131,-2.243758,4.044383,1.580663,2024-03-31,2024-08-19
8,Other Europe,NaN,306.763,0.879072,0.119771,0.498940,2.445412,0.152652,0.050463,4.449726,1.131792,0.213903,2.219749,0.687164,0.050463,4.750889,0.301162,2.946418,0.936609,2024-05-03,NaT
9,South America,NaN,437.691,0.536603,0.593052,0.310929,0.783645,0.081813,0.153109,2.535728,0.790593,0.869814,4.175129,0.321083,0.153109,6.576576,4.040848,1.679051,0.385570,2024-08-05,NaT
10,NaN,Low Income (LI),1041.411,0.283111,0.118751,0.226434,0.153857,0.029480,0.049707,0.886303,0.251958,0.182962,0.273968,0.062952,0.049707,0.840821,-0.045482,0.586872,1.054093,2025-09-13,2024-12-13
11,NaN,Lower-Middle Income (LM),2993.661,0.290005,0.059070,0.132348,0.543919,0.049073,0.053579,1.217702,0.277935,0.087658,0.158946,0.067611,0.053579,0.728074,-0.489628,0.806310,1.672497,2025-03-28,2024-08-06
12,NaN,Upper-Middle Income (UM),2715.682,0.556006,0.191415,0.273400,2.144860,0.090636,0.110876,3.379829,0.539539,0.252792,1.055115,0.179793,0.110876,2.151062,-1.228767,2.237978,1.571237,2024-06-12,2024-08-20
13,NaN,High Income (HI),1159.948,0.942990,0.241431,0.572666,3.443447,0.171503,0.089838,5.580231,0.940076,0.238226,1.124668,0.414657,0.089838,2.860617,-2.719614,3.694990,1.950709,2024-04-08,2024-07-06

In [16]:
# The regions we have in this dataset do not match with the regions of our regions.csv file, so we will have to
# do the calculations ourselves for each cathegory. First we will change the country names for their country_id and
# drop the regions column:

coun_fp.country = coun_fp.country.apply(to_proper_country_name) 

cc = pd.read_csv('../clean_data/countries.csv')

coun_fp['country'] = coun_fp['country'].apply(change_to_country_id) # New defined function to improve the process

coun_fp.columns = ['country_id','life_expectancy', 'region', 'income_group',
       'population_(millions)', 'cropland_footprint', 'grazing_footprint',
       'forest_product_footprint', 'carbon_footprint', 'fish_footprint',
       'built_up_land_1', 'total_ecological_footprint_(consumption)', 'cropland',
       'grazing_land', 'forest_land', 'fishing_ground', 'built_up_land',
       'total_biocapacity', 'ecological_(deficit)_or_reserve',
       'number_of_earths_required', 'number_of_countries_required',
       'official_country_overshoot_day',
       'official_country_ecological_deficit_day']

reg_fp.columns = ['region', 'income_group',
       'population_(millions)', 'cropland_footprint', 'grazing_footprint',
       'forest_product_footprint', 'carbon_footprint', 'fish_footprint',
       'built_up_land_1', 'total_ecological_footprint_(consumption)', 'cropland',
       'grazing_land', 'forest_land', 'fishing_ground', 'built_up_land',
       'total_biocapacity', 'ecological_(deficit)_or_reserve',
       'number_of_earths_required', 'number_of_countries_required',
       'official_country_overshoot_day',
       'official_country_ecological_deficit_day']

coun_fp = coun_fp.drop(columns = ['region','built_up_land_1'])
reg_fp = reg_fp.drop(columns = ['built_up_land_1'])


coun_fp

,country_id,life_expectancy,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official_country_overshoot_day,official_country_ecological_deficit_day
17,146,61,LI,40.754,0.417299,0.149562,0.055141,0.150524,0.000706,0.801465,0.327735,0.144313,0.012981,0.000565,0.028232,0.513827,-0.287638,0.530696,1.559795,NaT,2024-08-22
18,17,76,UM,2.866,0.803378,0.205494,0.205567,0.741158,0.042637,2.071238,0.600881,0.198147,0.223326,0.081392,0.073006,1.176752,-0.894486,1.371485,1.760131,2024-09-23,2024-07-26
19,144,76,UM,45.350,0.686809,0.158904,0.136541,1.179481,0.023458,2.222968,0.357129,0.237380,0.023912,0.007179,0.037775,0.663375,-1.559593,1.471955,3.350998,2024-09-04,2024-04-19
20,118,61,LM,35.027,0.231260,0.112594,0.081048,0.290260,0.081323,0.857846,0.151753,0.804692,0.416888,0.153499,0.061360,1.588191,0.730346,0.568029,0.540140,NaT,NaT
21,148,78,HI,0.100,NaN,NaN,NaN,NaN,NaN,2.936735,NaN,NaN,NaN,NaN,NaN,0.917277,-2.019458,1.944580,3.201578,2024-07-06,2024-04-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,191,70,UM,29.267,0.341907,0.619012,0.093140,0.935627,0.075966,2.109537,0.224860,0.612324,1.805861,0.259062,0.043885,2.945992,0.836455,1.396845,0.716070,2024-09-18,NaT
195,72,73,LM,98.954,0.528000,0.047851,0.382687,1.306666,0.088473,2.432274,0.401993,0.008851,0.155677,0.149952,0.078597,0.795070,-1.637204,1.610548,3.059195,2024-08-14,2024-04-29
196,192,63,LM,31.155,0.255308,0.100138,0.020945,0.158586,0.058752,0.613258,0.064427,0.086669,0.030011,0.146865,0.019530,0.347502,-0.265756,0.406073,1.764761,NaT,2024-07-26
197,85,71,LM,19.470,0.250613,0.099650,0.532439,0.233234,0.034109,1.213215,0.283922,0.667052,0.620781,0.016994,0.063170,1.651920,0.438705,0.803339,0.734427,NaT,NaT
198,45,71,LI,15.331,0.258499,0.270068,0.252568,0.273872,0.003414,1.085391,0.207019,0.270294,0.118373,0.008839,0.026970,0.631495,-0.453896,0.718700,1.718764,NaT,2024-07-31

In [17]:
# Now we will build the regions table will the adequate values. 
# First we save the income groups from the original table:

income_groups_fp = reg_fp.iloc[10:,1:].reset_index(drop = True)

income_groups_fp

,income_group,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required,number_of_countries_required,official_country_overshoot_day,official_country_ecological_deficit_day
0,Low Income (LI),1041.411,0.283111,0.118751,0.226434,0.153857,0.029480,0.886303,0.251958,0.182962,0.273968,0.062952,0.049707,0.840821,-0.045482,0.586872,1.054093,2025-09-13,2024-12-13
1,Lower-Middle Income (LM),2993.661,0.290005,0.059070,0.132348,0.543919,0.049073,1.217702,0.277935,0.087658,0.158946,0.067611,0.053579,0.728074,-0.489628,0.806310,1.672497,2025-03-28,2024-08-06
2,Upper-Middle Income (UM),2715.682,0.556006,0.191415,0.273400,2.144860,0.090636,3.379829,0.539539,0.252792,1.055115,0.179793,0.110876,2.151062,-1.228767,2.237978,1.571237,2024-06-12,2024-08-20
3,High Income (HI),1159.948,0.942990,0.241431,0.572666,3.443447,0.171503,5.580231,0.940076,0.238226,1.124668,0.414657,0.089838,2.860617,-2.719614,3.694990,1.950709,2024-04-08,2024-07-06

In [18]:
# Now to the regions:

coun_fp['region_id'] = coun_fp.country_id.apply(assign_region)

# coun_fp.region_id.unique()

world_fp = reg_fp.iloc[0,:].drop(columns = 'income_group')

reg_fp = reg_fp.reset_index(drop = True).iloc[:9,:].drop(columns = ['income_group',
                                                          'number_of_countries_required',
                                                          'official_country_overshoot_day',
                                                          'official_country_ecological_deficit_day'])

reg_fp.region = range(1,10)

reg_fp

,region,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required
0,1,7953.952,0.484741,0.125184,0.263549,1.561968,0.083496,2.581640,0.484741,0.183817,0.642539,0.136416,0.062704,1.510215,-1.071424,1.709451
1,2,7912.698,0.476041,0.139064,0.257655,1.466948,0.078694,2.556150,0.461295,0.178926,0.623182,0.156357,0.078036,1.547188,-1.008962,1.692573
2,3,1398.673,0.302925,0.149074,0.225587,0.273305,0.041939,1.154681,0.275737,0.270469,0.288532,0.067048,0.043207,0.971084,-0.183596,0.764580
3,4,4246.233,0.362665,0.066010,0.176103,1.458297,0.072242,2.230318,0.298066,0.074505,0.158629,0.093909,0.082460,0.722295,-1.508023,1.476821
4,5,92.253,0.405099,0.122843,0.259603,0.595334,0.109949,1.787487,0.277969,0.133192,0.279604,0.130305,0.106722,1.120296,-0.667191,1.183597
5,6,441.224,0.929712,0.211596,0.560173,2.211752,0.167982,4.457980,0.797165,0.123959,0.924284,0.208241,0.128910,2.227589,-2.230391,2.951884
6,7,485.043,0.599754,0.152830,0.121446,1.986622,0.071802,2.990365,0.449774,0.174052,0.139324,0.095078,0.057911,0.916138,-2.074228,1.980092
7,8,504.818,1.109494,0.270270,0.705764,3.853724,0.110021,6.107889,1.406469,0.244431,1.672629,0.481987,0.058616,3.864131,-2.243758,4.044383
8,9,306.763,0.879072,0.119771,0.498940,2.445412,0.152652,4.449726,1.131792,0.213903,2.219749,0.687164,0.050463,4.750889,0.301162,2.946418

In [19]:
sub_coun_fp = coun_fp[['country_id',
                       'region_id',
                       'population_(millions)',
                       'cropland_footprint',
                       'grazing_footprint',
                       'forest_product_footprint',
                       'carbon_footprint',
                       'fish_footprint',
                       'total_ecological_footprint_(consumption)',
                       'cropland',
                       'grazing_land',
                       'forest_land',
                       'fishing_ground',
                       'built_up_land',
                       'total_biocapacity']]

for i in range(3,sub_coun_fp.shape[1]): # We multiply by the population to get absolute gha values per country
    sub_coun_fp.iloc[:,i] = sub_coun_fp.iloc[:,i]*sub_coun_fp['population_(millions)']
    
for i in range(2,reg_fp.shape[1]-2): # Now we sum for each region and divide by sum of its countries populations
    for j in range(1,10):
        reg_fp.iloc[j-1,i] = (sub_coun_fp[sub_coun_fp.region_id == j].iloc[:,i+1].sum())/\
        (sub_coun_fp[sub_coun_fp.region_id == j].iloc[:,2].sum())
        reg_fp.iloc[j-1,1] = sub_coun_fp[sub_coun_fp.region_id == j].iloc[:,2].sum()
        
# We recalculate this:

reg_fp['ecological_(deficit)_or_reserve'] = reg_fp['total_biocapacity'] \
                                            - reg_fp['total_ecological_footprint_(consumption)'] 

# And this:

reg_fp['number_of_earths_required'] = reg_fp['total_ecological_footprint_(consumption)']/world_fp['total_biocapacity']

reg_fp

,region,population_(millions),cropland_footprint,grazing_footprint,forest_product_footprint,carbon_footprint,fish_footprint,total_ecological_footprint_(consumption),cropland,grazing_land,forest_land,fishing_ground,built_up_land,total_biocapacity,ecological_(deficit)_or_reserve,number_of_earths_required
0,1,545.543,0.893810,0.214662,0.536844,2.179877,0.157055,4.307397,0.730784,0.125723,0.841400,0.237052,0.124689,2.096067,-2.211330,2.852174
1,2,373.193,1.326863,0.294763,0.861377,4.810147,0.113185,7.456518,1.781522,0.254341,2.111809,0.605125,0.050184,4.802981,-2.653537,4.937387
2,3,660.419,0.510517,0.450229,0.295058,0.830127,0.089720,2.380692,0.631172,0.638188,2.891304,0.257478,0.132827,4.713369,2.332677,1.576392
3,4,235.915,0.613708,0.138628,0.192015,1.421231,0.030847,2.831746,0.634826,0.281140,0.304809,0.026341,0.040782,1.870202,-0.961544,1.875061
4,5,2410.928,0.453991,0.110748,0.231720,2.153964,0.115528,3.193282,0.346641,0.128327,0.263611,0.144122,0.105678,1.014181,-2.179101,2.114455
5,6,1185.738,0.309987,0.158229,0.252314,0.245863,0.044974,1.066403,0.299132,0.283568,0.311383,0.068710,0.047847,1.013292,-0.053111,0.706127
6,7,1961.798,0.258601,0.013693,0.098341,0.618609,0.020055,1.061651,0.243261,0.009271,0.021991,0.033593,0.052352,0.360468,-0.701183,0.702980
7,8,385.218,0.396310,0.128151,0.089533,1.349898,0.056293,2.459484,0.174447,0.099164,0.029142,0.094131,0.038878,0.522040,-1.937444,1.628565
8,9,145.806,1.221597,0.082095,0.667660,3.565114,0.238481,5.801172,1.948343,0.338902,4.210829,1.187786,0.026225,7.712084,1.910912,3.841288

In [20]:
world_fp = pd.DataFrame(world_fp.drop(index = 'income_group')).T
world_fp = world_fp.drop(columns = ['number_of_countries_required','official_country_ecological_deficit_day'])

In [21]:
for i in range(world_fp.shape[1]):
    world_fp.iloc[:,i] = world_fp.iloc[:,i].apply(to_num)

In [27]:
reg_fp.columns = ['region_id', 'population_(millions)', 'cropland_footprint',
       'grazing_footprint', 'forest_product_footprint', 'carbon_footprint',
       'fish_footprint', 'total_ecological_footprint_(consumption)',
       'cropland', 'grazing_land', 'forest_land', 'fishing_ground',
       'built_up_land', 'total_biocapacity', 'ecological_(deficit)_or_reserve',
       'number_of_earths_required']

coun_fp = coun_fp.drop(columns = 'region_id')

In [31]:
# Great! Let's save all this:

reg_fp.to_csv('../clean_data/regions_footprint.csv', index = False)
world_fp.to_csv('../clean_data/world_footprint.csv', index = False)
coun_fp.to_csv('../clean_data/countries_footprint.csv', index = False)
income_groups_fp.to_csv('../clean_data/income_groups_footprint.csv', index = False)